Added functional chat page and delete conversations endpoint
Gorchon/BrainyPad pull request #36
Opened 2024-06-10 10:01 UTC by Y0z64

Solves #29 

The query calls for the chat are not limited in any way shape or form, so actions as small as changing tabs will recall the entire conversation and load it again, which is not good for the performance.

I also made a mess of the url params when implementing the global chat, that needs to be fixed

- [x] Restrict chat query calls in some way
- [x] Add file references and reference count  
- [ ] Fix the global chat url params

Dont merge until all this points are solved

EDIT de Axel: Movi esto aca arriba para que salga el progreso de los ToDos

2024-06-10 10:03 UTC, Y0z64 commented
The query calls for the chat are not limited in any way shape or form, so actions as small as changing tabs will recall the entire conversation and load it again, which is not good for the performance.

- [ ] Restrict chat query calls in some way

2024-06-10 15:10 UTC, Gorchon reviewed
.'"'.        ___,,,___        .'``.
: (\  `."'"```         ```"'"-'  /) ;
 :  \                         `./  .'
  `.                            :.'
    /        _         _        \
   |         0}       {0         |
   |         /         \         |
   |        /           \        |
   |       /             \       |
    \     |      .-.      |     /
     `.   | . . /   \ . . |   .'
 jgs   `-._\.'.(     ).'./_.-'
           `\'  `._.'  '/'
             `. --'-- .'
               `-...-'

2024-06-12 00:50 UTC, adpadillar requested changes

2024-06-12 00:50 UTC, adpadillar commented on src/components/react/chat.tsx
> +        : `/api/assistant/chat/all`;
Why do we use the same endpoint (/api/assistant/chat/[id]) for this, when that is not what we had planned in the project documents before. These should be two separate endpoints.
1. (already was done) /api/assistant/chat/[id] to chat with a specific file/note
2. /api/assistant/chat to chat with all

2024-06-12 00:50 UTC, adpadillar commented on src/components/react/chat.tsx
> +      const endpoint = `/api/conversations/delete`;
This should probably be DELETE /api/conversations/[id], no need to send body or specify /delete

2024-06-12 00:50 UTC, adpadillar commented on src/pages/api/assistant/chat/[id].ts
> +      id !== "all"
I feel like we should follow the structure we had in the document and split the endpoints with a note/file and the endpoints without

2024-06-12 00:50 UTC, adpadillar commented on src/pages/api/files/delete.ts
>  import type { APIRoute } from "astro";
This endpoint should also probable be DELETE /api/files/[id], as we had in the original document

2024-06-12 01:34 UTC, adpadillar commented
Also, chat breaks when notes are returned as context (instead of files)

2024-06-12 06:00 UTC, Y0z64 commented
> Also, chat breaks when notes are returned as context (instead of files)

I thought you where only suposed to be able to talk with files so thats by bad

2024-06-12 23:40 UTC, adpadillar commented
Just merged my PR on this one because I needed your changes. This is what I changed
- [x]  **added functionality to search on files AND notes**
- [x] Improve UI for search preview on notes result
- [x] Improve logic around choosing the file to preview, ideally ask the model what would be the best file to display

2024-06-13 15:25 UTC, merged